### ISSUE TITLE
Can't open Film Packs, game crashes

### ISSUE THREAD

**Issue by Rukir** [dvrp0/reverie#1]
Notably, I am using this mod with the Bunco mod if that matters.
Image 1 is what I see before opening the pack. Image 2 is the crash log.

![image](https://github.com/dvrp0/reverie/assets/87564035/3dbf5793-5d8f-4eee-a098-0c663f8d1d5c)
![image2](https://github.com/dvrp0/reverie/assets/87564035/9a04499c-68ca-418e-8174-5cd334193072)

**Comment by SineSwiper** [comment]
I have a very similar error at the same file/line location.

**Comment by ETHO0730** [comment]
anybody know how to fix it?

**Comment by dvrp0** [comment]
This happens if Lovely haven't installed correctly or the modloader can't recognize Reverie's files.

Try reinstalling Lovely, Steamodded and mods following this instruction: https://dvrp-balatro-mods.pages.dev/install

**Comment by BalatroUser69** [comment]
I tried reinstalling Lovely, Steamodded and mods and it still won't work, has anyone fixed it?

**Comment by llslothIl** [comment]
I too am having almost the same issue where I can't load the decks or open the packs without the game crashing i had tried everything

**Comment by BalatroUser69** [comment]
Update: I fixed it by clicking Code and going to download zip instead of the website it takes you to and now it's working

**Comment by dvrp0** [comment]
Maybe the folders were nested? Lovely' doesn't load files if so
