### ISSUE TITLE
Game Crashes when mod is in the folder

### ISSUE THREAD

**Issue by nicholaspacini1** [dvrp0/reverie#2]
Lovely and steammodded latest additions downloaded (as of 15/5/24). No other mods are in this folder. I cannot start the game because these errors show up. 

![Screenshot (2)](https://github.com/dvrp0/reverie/assets/138745253/f3c0ec19-a451-416c-a326-ed19f93b538b)
![Screenshot (1)](https://github.com/dvrp0/reverie/assets/138745253/0584d918-d07c-4852-847b-d807adcc9744)

**Comment by dvrp0** [comment]
Try verifying file integrity on Steam

**Comment by nicholaspacini1** [comment]
Ok I tried that but steam 'reaquired' a file and deleted steammodded

**Comment by dvrp0** [comment]
Try installing with this guide https://dvrp-balatro-mods.pages.dev/install

**Comment by nicholaspacini1** [comment]
Aye that did the job, thx for the support mate
